
const f= ()=>{

try{
  let a=0
  t_9=_t_9=______
  console.log("progrm ran succesfully");
  return
   
}catch(error){

console.log("this is an error");
console.log(p);

}
finally{

 console.log("i am good boy");
 

}
}
f();
